Updated commands as per go-cli
razor-network/docs pull request #20
Opened 2021-08-01 14:49 UTC by adi44

2021-08-13 07:27 UTC, ashish10677 requested changes

2021-08-13 07:27 UTC, ashish10677 commented on docs/client.md
`create <password>` is a wrong command.
The command is `./razor create` that's all. The password is asked in the next step

2021-08-13 07:27 UTC, ashish10677 commented on docs/client.md
Also remove the warning after the create command.

2021-08-13 07:27 UTC, ashish10677 commented on docs/client.md
>  `-help` See a list of available commands
Can you separate all the commands with a heading, possibly h3, like:
### Help
`./razor --help` 
something like this

2021-08-13 07:27 UTC, ashish10677 commented on docs/client.md
> +Delegate some RAZORs
This is wrong. It should be activate delegation

2021-08-13 07:27 UTC, ashish10677 commented on docs/client.md
> +Activate Delegation
Headings are still not correct. The heading of command should come first, then the explanation and then the command.
### Activate Delegation
The staker can choose to activate delegation if he/she likes. 
```
./razor setDelegation  --address <address> --status <true_or_false> --commission <commission_percentage>
```

2021-08-13 07:27 UTC, ashish10677 commented on docs/index.md
> +A javascript reference client is being developed. It can be found here: [CLI](https://github.com/razor-network/razor-go)
It is a GoLang based CLI now. Not javascript.
Also, note that `##` is used carelessly in this file. Please fix those as well.

2021-09-28 10:06 UTC, ashish10677 approved these changes

2021-09-29 10:51 UTC, ashish10677 approved these changes

2021-10-11 08:22 UTC, SkandaBhat commented on docs/Quick Start/Delegate.md
> +Razor network is a proof of stake network. In order to participate in the network as a delegator, you will need to "Delegate" your RAZORs. RAZORs are the native tokens in the network and they are com
Explicity mention testnet

2021-10-11 08:24 UTC, SkandaBhat requested changes

2021-10-11 08:24 UTC, SkandaBhat commented on docs/index.md
Please add deployed addresses here as well

2022-01-14 07:46 UTC, merged